### ISSUE TITLE
no way to add journal entry 

### ISSUE THREAD

**Issue by ionosphere** [ekylibre/ekylibre#1638]
-- VERY VERY URGENT --

![saisie_1](https://cloud.githubusercontent.com/assets/1838491/22749866/14b2c0cc-ee2f-11e6-9108-bb7e062dcb7b.png)

![saisie_2](https://cloud.githubusercontent.com/assets/1838491/22749867/14b54568-ee2f-11e6-8e7c-89336368934e.png)

**Comment by Aquaj** [comment]
Apparently fixed by 84ccbe02.

**Comment by ionosphere** [comment]
I ve always have mistake on journal entry. On each update, entry items are duplicated.

![duplicate_entries](https://cloud.githubusercontent.com/assets/1838491/22795130/d652e3f8-eef5-11e6-9179-5ecea610ec4c.png)

![duplicate_2](https://cloud.githubusercontent.com/assets/1838491/22795191/19d0a08e-eef6-11e6-9db8-db7e220b1aef.png)

**Comment by ionosphere** [comment]
Not completely solved because, it doesn't work in case of deleting one entry and add 2 other and then save entry. We have the message "The entry is not balanced".

**Comment by thib44** [comment]
Resolved with : 
https://github.com/ekylibre/ekylibre/pull/1812
