### ISSUE TITLE
Informations are no longer fulfilled automatically at creation of a new inspection

### ISSUE THREAD

**Issue by EmmaDorie** [ekylibre/ekylibre#988]
When product is selected, informations expected are : 
-  application_width 
- rows count
- net surface area
![chasse-aux-bugs nouvel agreage 2016-08-05 10-36-42](https://cloud.githubusercontent.com/assets/11627573/17431488/89b72b74-5afa-11e6-9d79-bb063c8eb964.png)

**Comment by Aquaj** [comment]
I fixed some bugs pertaining to that issue in ab689c3 and everything works on my side. If it's okay on your side too we'll close this :smile:

**Comment by burisu** [comment]
I close for now, @EmmaDorie I let you re-open the issue if you have any trouble

**Comment by EmmaDorie** [comment]
Issue still persist on my side ...  application_width and rows_count are false and net_surface_area stay empty.
